export enum AgentStatus {
  ACTIVE = 'ACTIVE',
  DISABLED = 'DISABLED',
}

export enum TreasuryStatus {
  ACTIVE = 'ACTIVE',
  FROZEN = 'FROZEN',
}

export enum SpendRequestStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REQUIRES_APPROVAL = 'REQUIRES_APPROVAL',
  REJECTED = 'REJECTED',
  EXECUTED = 'EXECUTED',
  FAILED = 'FAILED',
}

export enum PolicyDecision {
  APPROVED = 'APPROVED',
  REQUIRES_APPROVAL = 'REQUIRES_APPROVAL',
  REJECTED = 'REJECTED',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AuditEventType {
  AGENT_REGISTERED = 'AGENT_REGISTERED',
  AGENT_DISABLED = 'AGENT_DISABLED',
  AGENT_ENABLED = 'AGENT_ENABLED',
  KILL_SWITCH_ACTIVATED = 'KILL_SWITCH_ACTIVATED',
  KILL_SWITCH_DEACTIVATED = 'KILL_SWITCH_DEACTIVATED',
  SPEND_REQUEST_SUBMITTED = 'SPEND_REQUEST_SUBMITTED',
  SPEND_REQUEST_APPROVED = 'SPEND_REQUEST_APPROVED',
  SPEND_REQUEST_REJECTED = 'SPEND_REQUEST_REJECTED',
  SPEND_REQUEST_REQUIRES_APPROVAL = 'SPEND_REQUEST_REQUIRES_APPROVAL',
  SPEND_REQUEST_EXECUTED = 'SPEND_REQUEST_EXECUTED',
  SPEND_REQUEST_FAILED = 'SPEND_REQUEST_FAILED',
  APPROVAL_REQUESTED = 'APPROVAL_REQUESTED',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_DENIED = 'APPROVAL_DENIED',
  POLICY_ASSIGNED = 'POLICY_ASSIGNED',
  BUDGET_CREATED = 'BUDGET_CREATED',
  TREASURY_CREATED = 'TREASURY_CREATED',
  TREASURY_FUNDED = 'TREASURY_FUNDED',
  TREASURY_FROZEN = 'TREASURY_FROZEN',
}

export enum ActorType {
  AGENT = 'AGENT',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
  APPROVER = 'APPROVER',
}

export enum SolanaNetwork {
  DEVNET = 'devnet',
  MAINNET = 'mainnet-beta',
}

export enum Currency {
  USDC = 'USDC',
  SOL = 'SOL',
}
